dist: trusty
sudo: false
language: generic

# # safelist
# branches:
#   only:
#   - harvard

addons:
  apt:
    packages:
    - iverilog
    - clang
    - libftdi-dev

cache:
  directories:
    - ~/toolchain

before_install:
install:
  - make ci-deps

before_script:
#   - cd verilog
script:
  - PATH=~/toolchain/bin:$PATH make test

after_success:
after_failure:
  # Upload files for debug.
  #  - echo "Uploading up to 4 failure traces for debug" && for FILE in `ls /home/travis/build/stevehoover/warp-v/formal/checks/*/FAIL | head -n 4`; do curl --upload-file `echo $FILE | sed s/FAIL$//`engine_0/trace.vcd https://transfer.sh/`echo $FILE | sed 's/^.*\/\([^\/]*\)\/FAIL$/\1/'`_trace.vcd && echo; done
after_script:
  # Report a message if we didn't use the latest commit of yosys.
  # - if cmp -s yosys_latest_commit_id.txt env/yosys_commit_id.txt; then echo '******** Using the following cached yosys (https://github.com/cliffordwolf/yosys.git) commit ID which is not the latest. Consider clearing Travis cache. **********' && cat env/yosys_commit_id.txt && echo '**********'; fi
