#!/bin/bash

MODULE=$1
INCLUDE=

case ${MODULE} in
FOO)
  INCLUDE=
  ;;
esac

iverilog -o ${MODULE}.vcd ${MODULE}_tb.v ${MODULE}.v ${INCLUDE} &&
  ./${MODULE}.vcd &&
  gtkwave ${MODULE}_tb.vcd ${MODULE}_tb.gtkw
